export type Race = {
  Driver: string;
  Sakhir: string;
  Jeddah: string;
  Melbourne: string;
  Baku: string;
  Miami: string;
  Monaco: string;
  Barcelona: string;
  Montreal: string;
  Spielberg: string;
  Silverstone: string;
  Mogyoród: string;
  Spa: string;
  Zandvoort: string;
  Monza: string;
  Singapore: string;
  Suzuka: string;
  Lusail: string;
  Austin: string;
  "Mexico City": string;
  "Sao Paulo": string;
  "Las Vegas": string;
  "Abu Dhabi": string;
  Points: string;
};

export const races: Race[] = [
  {
    Driver: "Max Verstappen",
    Sakhir: "1",
    Jeddah: "2",
    Melbourne: "1",
    Baku: "2",
    Miami: "1",
    Monaco: "1",
    Barcelona: "1",
    Montreal: "1",
    Spielberg: "1",
    Silverstone: "1",
    Mogyoród: "1",
    Spa: "1",
    Zandvoort: "1",
    Monza: "1",
    Singapore: "5",
    Suzuka: "1",
    Lusail: "1",
    Austin: "1",
    "Mexico City": "1",
    "Sao Paulo": "1",
    "Las Vegas": "1",
    "Abu Dhabi": "1",
    Points: "575",
  },
  {
    Driver: "Sergio Perez",
    Sakhir: "2",
    Jeddah: "1",
    Melbourne: "5",
    Baku: "1",
    Miami: "2",
    Monaco: "16",
    Barcelona: "4",
    Montreal: "6",
    Spielberg: "3",
    Silverstone: "6",
    Mogyoród: "3",
    Spa: "2",
    Zandvoort: "4",
    Monza: "2",
    Singapore: "8",
    Suzuka: "Ret",
    Lusail: "10",
    Austin: "4",
    "Mexico City": "Ret",
    "Sao Paulo": "4",
    "Las Vegas": "3",
    "Abu Dhabi": "4",
    Points: "285",
  },
  {
    Driver: "Lewis Hamilton",
    Sakhir: "5",
    Jeddah: "5",
    Melbourne: "2",
    Baku: "6",
    Miami: "6",
    Monaco: "4",
    Barcelona: "2",
    Montreal: "3",
    Spielberg: "8",
    Silverstone: "3",
    Mogyoród: "4",
    Spa: "4",
    Zandvoort: "6",
    Monza: "6",
    Singapore: "3",
    Suzuka: "5",
    Lusail: "Ret",
    Austin: "DSQ",
    "Mexico City": "2",
    "Sao Paulo": "8",
    "Las Vegas": "7",
    "Abu Dhabi": "9",
    Points: "234",
  },
  {
    Driver: "Fernando Alonso",
    Sakhir: "3",
    Jeddah: "3",
    Melbourne: "3",
    Baku: "4",
    Miami: "3",
    Monaco: "2",
    Barcelona: "7",
    Montreal: "2",
    Spielberg: "5",
    Silverstone: "7",
    Mogyoród: "9",
    Spa: "5",
    Zandvoort: "2",
    Monza: "9",
    Singapore: "15",
    Suzuka: "8",
    Lusail: "6",
    Austin: "Ret",
    "Mexico City": "Ret",
    "Sao Paulo": "3",
    "Las Vegas": "9",
    "Abu Dhabi": "7",
    Points: "206",
  },
  {
    Driver: "Charles Leclerc",
    Sakhir: "Ret",
    Jeddah: "7",
    Melbourne: "Ret",
    Baku: "3",
    Miami: "7",
    Monaco: "6",
    Barcelona: "11",
    Montreal: "4",
    Spielberg: "2",
    Silverstone: "9",
    Mogyoród: "7",
    Spa: "3",
    Zandvoort: "Ret",
    Monza: "4",
    Singapore: "4",
    Suzuka: "4",
    Lusail: "5",
    Austin: "DSQ",
    "Mexico City": "3",
    "Sao Paulo": "DNS",
    "Las Vegas": "2",
    "Abu Dhabi": "2",
    Points: "206",
  },
  {
    Driver: "Lando Norris",
    Sakhir: "17",
    Jeddah: "17",
    Melbourne: "6",
    Baku: "9",
    Miami: "17",
    Monaco: "9",
    Barcelona: "17",
    Montreal: "13",
    Spielberg: "4",
    Silverstone: "2",
    Mogyoród: "2",
    Spa: "7",
    Zandvoort: "7",
    Monza: "8",
    Singapore: "2",
    Suzuka: "2",
    Lusail: "3",
    Austin: "2",
    "Mexico City": "5",
    "Sao Paulo": "2",
    "Las Vegas": "Ret",
    "Abu Dhabi": "5",
    Points: "205",
  },
  {
    Driver: "Carlos Sainz Jr.",
    Sakhir: "4",
    Jeddah: "6",
    Melbourne: "12",
    Baku: "5",
    Miami: "5",
    Monaco: "8",
    Barcelona: "5",
    Montreal: "5",
    Spielberg: "6",
    Silverstone: "10",
    Mogyoród: "8",
    Spa: "Ret",
    Zandvoort: "5",
    Monza: "3",
    Singapore: "1",
    Suzuka: "6",
    Lusail: "DNS",
    Austin: "3",
    "Mexico City": "4",
    "Sao Paulo": "6",
    "Las Vegas": "6",
    "Abu Dhabi": "18",
    Points: "200",
  },
  {
    Driver: "George Russel",
    Sakhir: "7",
    Jeddah: "4",
    Melbourne: "Ret",
    Baku: "8",
    Miami: "4",
    Monaco: "5",
    Barcelona: "3",
    Montreal: "Ret",
    Spielberg: "7",
    Silverstone: "5",
    Mogyoród: "6",
    Spa: "6",
    Zandvoort: "17",
    Monza: "5",
    Singapore: "16",
    Suzuka: "7",
    Lusail: "4",
    Austin: "5",
    "Mexico City": "6",
    "Sao Paulo": "Ret",
    "Las Vegas": "8",
    "Abu Dhabi": "3",
    Points: "175",
  },
  {
    Driver: "Oscar Piastri",
    Sakhir: "Ret",
    Jeddah: "15",
    Melbourne: "8",
    Baku: "11",
    Miami: "19",
    Monaco: "10",
    Barcelona: "13",
    Montreal: "11",
    Spielberg: "16",
    Silverstone: "4",
    Mogyoród: "5",
    Spa: "Ret",
    Zandvoort: "9",
    Monza: "12",
    Singapore: "7",
    Suzuka: "3",
    Lusail: "2",
    Austin: "Ret",
    "Mexico City": "8",
    "Sao Paulo": "14",
    "Las Vegas": "10",
    "Abu Dhabi": "6",
    Points: "97",
  },
  {
    Driver: "Lance Stroll",
    Sakhir: "6",
    Jeddah: "Ret",
    Melbourne: "4",
    Baku: "7",
    Miami: "12",
    Monaco: "Ret",
    Barcelona: "6",
    Montreal: "9",
    Spielberg: "9",
    Silverstone: "14",
    Mogyoród: "10",
    Spa: "9",
    Zandvoort: "11",
    Monza: "16",
    Singapore: "WD",
    Suzuka: "Ret",
    Lusail: "11",
    Austin: "7",
    "Mexico City": "17",
    "Sao Paulo": "5",
    "Las Vegas": "5",
    "Abu Dhabi": "10",
    Points: "74",
  },
  {
    Driver: "Pierre Gasly",
    Sakhir: "9",
    Jeddah: "9",
    Melbourne: "13",
    Baku: "14",
    Miami: "8",
    Monaco: "7",
    Barcelona: "10",
    Montreal: "12",
    Spielberg: "10",
    Silverstone: "18",
    Mogyoród: "Ret",
    Spa: "11",
    Zandvoort: "3",
    Monza: "15",
    Singapore: "6",
    Suzuka: "10",
    Lusail: "12",
    Austin: "6",
    "Mexico City": "11",
    "Sao Paulo": "7",
    "Las Vegas": "11",
    "Abu Dhabi": "13",
    Points: "62",
  },
  {
    Driver: "Esteban Ocon",
    Sakhir: "Ret",
    Jeddah: "8",
    Melbourne: "14",
    Baku: "15",
    Miami: "9",
    Monaco: "3",
    Barcelona: "8",
    Montreal: "8",
    Spielberg: "14",
    Silverstone: "Ret",
    Mogyoród: "Ret",
    Spa: "8",
    Zandvoort: "10",
    Monza: "Ret",
    Singapore: "Ret",
    Suzuka: "9",
    Lusail: "7",
    Austin: "Ret",
    "Mexico City": "10",
    "Sao Paulo": "10",
    "Las Vegas": "4",
    "Abu Dhabi": "12",
    Points: "58",
  },
  {
    Driver: "Alexander Albon",
    Sakhir: "10",
    Jeddah: "Ret",
    Melbourne: "Ret",
    Baku: "12",
    Miami: "14",
    Monaco: "14",
    Barcelona: "16",
    Montreal: "7",
    Spielberg: "11",
    Silverstone: "8",
    Mogyoród: "11",
    Spa: "14",
    Zandvoort: "8",
    Monza: "7",
    Singapore: "11",
    Suzuka: "Ret",
    Lusail: "13",
    Austin: "9",
    "Mexico City": "9",
    "Sao Paulo": "Ret",
    "Las Vegas": "12",
    "Abu Dhabi": "14",
    Points: "27",
  },
  {
    Driver: "Yuki Tsunoda",
    Sakhir: "11",
    Jeddah: "11",
    Melbourne: "10",
    Baku: "10",
    Miami: "11",
    Monaco: "15",
    Barcelona: "12",
    Montreal: "14",
    Spielberg: "19",
    Silverstone: "16",
    Mogyoród: "15",
    Spa: "10",
    Zandvoort: "15",
    Monza: "DNS",
    Singapore: "Ret",
    Suzuka: "12",
    Lusail: "15",
    Austin: "8",
    "Mexico City": "12",
    "Sao Paulo": "9",
    "Las Vegas": "18",
    "Abu Dhabi": "8",
    Points: "17",
  },
  {
    Driver: "Valtteri Bottas",
    Sakhir: "8",
    Jeddah: "18",
    Melbourne: "11",
    Baku: "18",
    Miami: "13",
    Monaco: "11",
    Barcelona: "19",
    Montreal: "10",
    Spielberg: "15",
    Silverstone: "12",
    Mogyoród: "12",
    Spa: "12",
    Zandvoort: "14",
    Monza: "10",
    Singapore: "Ret",
    Suzuka: "Ret",
    Lusail: "8",
    Austin: "12",
    "Mexico City": "15",
    "Sao Paulo": "Ret",
    "Las Vegas": "17",
    "Abu Dhabi": "19",
    Points: "10",
  },
  {
    Driver: "Nico Hülkenberg",
    Sakhir: "15",
    Jeddah: "12",
    Melbourne: "7",
    Baku: "17",
    Miami: "15",
    Monaco: "17",
    Barcelona: "15",
    Montreal: "15",
    Spielberg: "Ret",
    Silverstone: "13",
    Mogyoród: "14",
    Spa: "18",
    Zandvoort: "12",
    Monza: "17",
    Singapore: "13",
    Suzuka: "14",
    Lusail: "16",
    Austin: "11",
    "Mexico City": "13",
    "Sao Paulo": "12",
    "Las Vegas": "19",
    "Abu Dhabi": "15",
    Points: "",
  },
  {
    Driver: "Daniel Ricciardo",
    Sakhir: "",
    Jeddah: "",
    Melbourne: "",
    Baku: "",
    Miami: "",
    Monaco: "",
    Barcelona: "",
    Montreal: "",
    Spielberg: "",
    Silverstone: "",
    Mogyoród: "13",
    Spa: "16",
    Zandvoort: "WD",
    Monza: "",
    Singapore: "",
    Suzuka: "",
    Lusail: "",
    Austin: "",
    "Mexico City": "7",
    "Sao Paulo": "13",
    "Las Vegas": "14",
    "Abu Dhabi": "15",
    Points: "6",
  },
  {
    Driver: "Zhou Guanyu",
    Sakhir: "16",
    Jeddah: "13",
    Melbourne: "9",
    Baku: "Ret",
    Miami: "16",
    Monaco: "13",
    Barcelona: "9",
    Montreal: "16",
    Spielberg: "12",
    Silverstone: "15",
    Mogyoród: "16",
    Spa: "13",
    Zandvoort: "Ret",
    Monza: "14",
    Singapore: "12",
    Suzuka: "13",
    Lusail: "9",
    Austin: "13",
    "Mexico City": "14",
    "Sao Paulo": "Ret",
    "Las Vegas": "15",
    "Abu Dhabi": "17",
    Points: "6",
  },
  {
    Driver: "Kevin Magnussen",
    Sakhir: "13",
    Jeddah: "10",
    Melbourne: "17",
    Baku: "13",
    Miami: "10",
    Monaco: "19",
    Barcelona: "18",
    Montreal: "17",
    Spielberg: "18",
    Silverstone: "Ret",
    Mogyoród: "17",
    Spa: "15",
    Zandvoort: "16",
    Monza: "18",
    Singapore: "10",
    Suzuka: "15",
    Lusail: "14",
    Austin: "14",
    "Mexico City": "Ret",
    "Sao Paulo": "Ret",
    "Las Vegas": "13",
    "Abu Dhabi": "20",
    Points: "3",
  },
  {
    Driver: "Liam Lawson",
    Sakhir: "",
    Jeddah: "",
    Melbourne: "",
    Baku: "",
    Miami: "",
    Monaco: "",
    Barcelona: "",
    Montreal: "",
    Spielberg: "",
    Silverstone: "",
    Mogyoród: "",
    Spa: "",
    Zandvoort: "13",
    Monza: "11",
    Singapore: "9",
    Suzuka: "11",
    Lusail: "17",
    Austin: "",
    "Mexico City": "",
    "Sao Paulo": "",
    "Las Vegas": "",
    "Abu Dhabi": "",
    Points: "2",
  },
  {
    Driver: "Logan Sargeant",
    Sakhir: "12",
    Jeddah: "16",
    Melbourne: "16",
    Baku: "16",
    Miami: "20",
    Monaco: "18",
    Barcelona: "20",
    Montreal: "Ret",
    Spielberg: "13",
    Silverstone: "11",
    Mogyoród: "18",
    Spa: "17",
    Zandvoort: "Ret",
    Monza: "13",
    Singapore: "14",
    Suzuka: "Ret",
    Lusail: "Ret",
    Austin: "10",
    "Mexico City": "16",
    "Sao Paulo": "11",
    "Las Vegas": "16",
    "Abu Dhabi": "16",
    Points: "1",
  },
  {
    Driver: "Nyck de Vries",
    Sakhir: "14",
    Jeddah: "14",
    Melbourne: "15",
    Baku: "Ret",
    Miami: "18",
    Monaco: "12",
    Barcelona: "14",
    Montreal: "18",
    Spielberg: "17",
    Silverstone: "17",
    Mogyoród: "",
    Spa: "",
    Zandvoort: "",
    Monza: "",
    Singapore: "",
    Suzuka: "",
    Lusail: "",
    Austin: "",
    "Mexico City": "",
    "Sao Paulo": "",
    "Las Vegas": "",
    "Abu Dhabi": "",
    Points: "0",
  },
];
